name: Deploy to Google Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Authenticate to Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CI_JSON }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Google App Engine
        id: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          version: prod
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |-
            FUSION_API_KEY=${{ secrets.FUSION_API_KEY }}
